# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30)),
                ('car_plate', models.CharField(max_length=10, unique=True)),
                ('no_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('national_id', models.IntegerField(unique=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Car')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driverLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.DriverLocation'),
        ),
    ]
