# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='drivers/'),
            preserve_default=False,
        ),
    ]
